# Generated by Django 4.2.4 on 2023-10-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_solicitudes_fecha_de_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_de_solicitud',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
