# Generated by Django 4.2.4 on 2023-11-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_solicitudes_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='categoria',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
