# Generated by Django 4.2.4 on 2023-11-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_solicitudes_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pymeAsociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.pymes'),
        ),
    ]
