# Generated by Django 4.2.4 on 2023-11-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_alter_productos_pymeasociada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pymes',
            name='logo',
        ),
        migrations.AddField(
            model_name='pymes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='logoPymes'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='logoPymesSoli'),
        ),
    ]
