# Generated by Django 4.2.4 on 2023-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_remove_pymes_logo_pymes_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
