# Generated by Django 4.2.4 on 2023-11-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.IntegerField(default=1),
        ),
    ]
