# Generated by Django 4.2.4 on 2023-11-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
