# Generated by Django 4.2.4 on 2023-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_alter_solicitudes_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='idSolicitante',
            field=models.IntegerField(default=None),
        ),
    ]
