# Generated by Django 4.2.4 on 2023-11-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_solicitudes_idsolicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='idSolicitante',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
