# Generated by Django 4.2.4 on 2023-11-16 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0013_productos_cantidad_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='producto_id',
            field=models.ManyToManyField(to='mainPage.productos'),
        ),
    ]
