# Generated by Django 4.2.4 on 2023-11-16 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0014_pedidos_usuario_id_remove_pedidos_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
