# Generated by Django 4.2.4 on 2023-11-16 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0015_remove_pedidos_usuario_id_pedidos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='cantidadProduc',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.productos')),
            ],
            options={
                'verbose_name': 'Detalle_Pedido',
                'db_table': 'detalle_pedidos',
            },
        ),
        migrations.AddField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(through='mainPage.DetallePedido', to='mainPage.productos'),
        ),
    ]
