# Generated by Django 4.2.4 on 2023-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0016_remove_pedidos_cantidadproduc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
