# Generated by Django 4.2.4 on 2023-11-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0018_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='productos',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
