# Generated by Django 4.2.4 on 2023-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0021_itempedido_pedido_delete_carrito_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
